source ~/.dotfiles/aliases.sh
source ~/.dotfiles/env.sh
source ~/.dotfiles/goenv.sh
source ~/.dotfiles/key-bindings.sh
source ~/.dotfiles/nvm.sh
source ~/.dotfiles/python.sh
source ~/.dotfiles/ruby.sh
source ~/.dotfiles/scripts.sh
source ~/.dotfiles/zsh.sh
