export EDITOR=vi
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
export EMACS=/Applications/Emacs.app/Contents/MacOS/emacs
export NO_WEBPACK_COMPILE_CHECK=1
export SKIP_TEST_TIMEOUT=1
export LOG_PRODUCT_FEATURES_TO_DB=false
export SAVEHIST=1000000
export HISTFILE=~/.zsh_history
setopt APPEND_HISTORY
