[settings]
idiomatic_version_file_enable_tools = []
experimental = true

[settings.ruby]
compile = false

[tools]
go = "latest"
java = "25"
node = "22.16.0"
python = "3"
ruby = "4.0.1"
yarn = "latest"
