[settings]
idiomatic_version_file_enable_tools = []
experimental = true

[tools]
go = "latest"

java = "25"

node = {
  version = "latest",
  postinstall = "xargs npm i -g < ~/.config/mise/default-packages/npm"
}

python = "3"

ruby = {
  version = "latest",
  postinstall = "xargs gem install < ~/.config/mise/default-packages/ruby"
}

yarn = "latest"
