(let ((jake-pink "#fc199a")
      (jake-yellow "#d1b539")
      (jake-dark "#200933")
      (jake-darkest "#1D0432")
      (jake-green "#a5ff90")
      (jake-cyan "#61e2ff")
      (jake-cyan-highlight "#9EFFFF")
      (jake-purple-dark "#371057")
      (jake-purple "#9963ff")
      (jake-purple-subtle "#574497")
      )


  (set-face-attribute 'default nil :family "MonaspiceAr Nerd Font" :height 120 :weight 'light)
  (load-theme 'jakewave t)
  (load-theme 'jakewave t) ;; Necessary, but why? 🤷‍♂️

  (setq xterm-color-names
        (vconcat (list jake-darkest jake-pink jake-green jake-yellow jake-purple jake-purple jake-cyan jake-cyan)))
  (setq xterm-color-names-bright
        (vconcat (list jake-purple-subtle jake-pink jake-green jake-yellow jake-purple jake-purple jake-cyan jake-cyan)))

  (set-face-attribute 'jake-no-glow nil :shadow nil)
  (set-face-attribute 'jake-cyan nil :shadow nil)
  (set-face-attribute 'jake-green nil :shadow nil)
  (set-face-attribute 'jake-pink nil :shadow nil)
  (set-face-attribute 'jake-purple nil :shadow nil)
  (set-face-attribute 'jake-purple-subtle nil :shadow nil)
  (set-face-attribute 'jake-yellow nil :shadow nil)

  (set-face-attribute 'jake-cyan-glow nil :shadow `(10.0 ,jake-cyan 0 . 0))
  (set-face-attribute 'jake-cyan-highlight-glow nil :shadow `(10.0 ,jake-cyan-highlight 0 . 0))
  (set-face-attribute 'jake-green-glow nil :shadow `(10.0 ,jake-green 0 . 0))
  (set-face-attribute 'jake-pink-glow nil :shadow `(10.0 ,jake-pink 0 . 0))
  (set-face-attribute 'jake-purple-glow nil :shadow `(10.0 ,jake-purple 0 . 0))
  (set-face-attribute 'jake-purple-subtle-glow nil :shadow `(5.0 ,jake-purple-subtle 0 . 0))
  (set-face-attribute 'jake-yellow-glow nil :shadow `(10.0 ,jake-yellow 0 . 0))
  (set-face-attribute 'line-number nil :shadow '(10.0 "#4A1E64" 0 . 0))
  (set-face-attribute 'line-number-current-line nil :shadow '(10.0 "#7912ce" 0 . 0))

  (set-face-attribute 'nerd-icons-blue nil :shadow nil)
  (set-face-attribute 'nerd-icons-blue-alt nil :shadow nil)
  (set-face-attribute 'nerd-icons-cyan nil :shadow nil)
  (set-face-attribute 'nerd-icons-cyan-alt nil :shadow nil)
  (set-face-attribute 'nerd-icons-dblue nil :shadow nil)
  (set-face-attribute 'nerd-icons-dcyan nil :shadow nil)
  (set-face-attribute 'nerd-icons-dgreen nil :shadow nil)
  (set-face-attribute 'nerd-icons-dmaroon nil :shadow nil)
  (set-face-attribute 'nerd-icons-dorange nil :shadow nil)
  (set-face-attribute 'nerd-icons-dpink nil :shadow nil)
  (set-face-attribute 'nerd-icons-dpurple nil :shadow nil)
  (set-face-attribute 'nerd-icons-dred nil :shadow nil)
  (set-face-attribute 'nerd-icons-dsilver nil :shadow nil)
  (set-face-attribute 'nerd-icons-dyellow nil :shadow nil)
  (set-face-attribute 'nerd-icons-green nil :shadow nil)
  (set-face-attribute 'nerd-icons-lblue nil :shadow nil)
  (set-face-attribute 'nerd-icons-lcyan nil :shadow nil)
  (set-face-attribute 'nerd-icons-lgreen nil :shadow nil)
  (set-face-attribute 'nerd-icons-lmaroon nil :shadow nil)
  (set-face-attribute 'nerd-icons-lorange nil :shadow nil)
  (set-face-attribute 'nerd-icons-lpink nil :shadow nil)
  (set-face-attribute 'nerd-icons-lpurple nil :shadow nil)
  (set-face-attribute 'nerd-icons-lred nil :shadow nil)
  (set-face-attribute 'nerd-icons-lsilver nil :shadow nil)
  (set-face-attribute 'nerd-icons-lyellow nil :shadow nil)
  (set-face-attribute 'nerd-icons-maroon nil :shadow nil)
  (set-face-attribute 'nerd-icons-orange nil :shadow nil)
  (set-face-attribute 'nerd-icons-pink nil :shadow nil)
  (set-face-attribute 'nerd-icons-purple nil :shadow nil)
  (set-face-attribute 'nerd-icons-purple-alt nil :shadow nil)
  (set-face-attribute 'nerd-icons-red nil :shadow nil)
  (set-face-attribute 'nerd-icons-red-alt nil :shadow nil)
  (set-face-attribute 'nerd-icons-silver nil :shadow nil)
  (set-face-attribute 'nerd-icons-yellow nil :shadow nil)
  )
