(setq typescript-fmt-on-save t)
(setq typescript-fmt-tool 'prettier)
(setq typescript-indent-level 2)
(setq typescript-linter 'eslint)

(setq mu4e-installation-path (getenv "MU4E_DIR"))
(setq mu4e-get-mail-command "mbsync -a")
(setq mu4e-update-interval (* 5 60))
(setq mu4e-change-filenames-when-moving t)

(setq git-enable-magit-delta-plugin t)
(setq git-magit-status-fullscreen t)

(setq org-agenda-files '("~/Org/Tasks.org" "~/Org/Journal/"))
(setq org-archive-location "~/Org/Archive.org::datetree/")
(setq org-ellipsis " ▾")
(setq org-enable-org-journal-support t)
(setq org-hide-emphasis-markers t)
(setq org-journal-dir "~/Org/Journal/")
(setq org-journal-file-format "%Y-%m-%d.org")
(setq org-journal-time-format "")
(setq org-journal-time-prefix "** TODO ")
(setq org-log-done 'time)
(setq org-log-into-drawer t)
(setq org-refile-targets '((org-agenda-files :maxlevel . 1)))
(setq org-superstar-headline-bullets-list '("" "●" "○" "◦" "•" "◦" "•"))
(setq org-superstar-item-bullet-alist '((?+ . ?•) (?* . ?•) (?- . ?•)))
(setq org-tags-column 1)
(setq org-todo-keywords '((sequence "TODO" "|" "DONE" "REJECTED")))

(setq shell-default-height 30)
(setq shell-default-position 'bottom)
