(setq gptel-model 'gpt-4o-mini)

(setq javascript-backend 'lsp)
(setq javascript-fmt-on-save t)
(setq javascript-fmt-tool 'prettier)
(setq javascript-indent-level 2)
(setq javascript-linter 'eslint)
(setq javascript-lsp-linter nil)
(setq js2-mode-show-strict-warnings nil)
(setq typescript-fmt-on-save t)
(setq typescript-fmt-tool 'prettier)
(setq typescript-indent-level 2)
(setq typescript-linter 'eslint)

(setq web-mode-markup-indent-offset 2)
(setq web-mode-css-indent-offset 2)
(setq web-mode-code-indent-offset 2)

(setq mu4e-installation-path (getenv "MU4E_DIR"))
(setq mu4e-get-mail-command "mbsync -a")
(setq mu4e-update-interval (* 5 60))
(setq mu4e-change-filenames-when-moving t)

(setq git-enable-magit-delta-plugin t)
(setq git-magit-status-fullscreen t)
(setq magit-delta-hide-plus-minus-markers nil)

(setq org-agenda-files '("~/Org/Tasks.org" "~/Org/Journal/"))
(setq org-archive-location "~/Org/Archive.org::datetree/")
(setq org-ellipsis " ▾")
(setq org-enable-org-journal-support t)
(setq org-hide-emphasis-markers t)
(setq org-journal-dir "~/Org/Journal/")
(setq org-journal-file-format "%Y-%m-%d.org")
(setq org-journal-time-format "")
(setq org-journal-time-prefix "** TODO ")
(setq org-log-done 'time)
(setq org-log-into-drawer t)
(setq org-refile-targets '((org-agenda-files :maxlevel . 1)))
(setq org-superstar-headline-bullets-list '("" "●" "○" "◦" "•" "◦" "•"))
(setq org-superstar-item-bullet-alist '((?+ . ?•) (?* . ?•) (?- . ?•)))
(setq org-tags-column 1)
(setq org-todo-keywords '((sequence "TODO" "|" "DONE" "REJECTED")))

(setq slack-enable-global-mode-string t)
(setq slack-modeline-count-only-subscribed-channel nil)
(setq slack-prefer-current-team t)

(setq shell-default-height 30)
(setq shell-default-position 'bottom)
