((ruby-mode . ((lsp-sorbet-use-bundler . t)
               (lsp-sorbet-as-add-on . t)
               (lsp-disabled-clients . (rubocop-ls ruby-ls))
               (projectile-project-type . rails-test)
               (ruby-test-rails-test-command . "bin/spring rails test")
               (flycheck-reekrc . "~/.config/jake/projects/meetcleo/meetcleo/reek.yml"))))
