((ruby-ts-mode . ((lsp-sorbet-use-bundler . t)
                  (lsp-sorbet-as-add-on . t)
                  (lsp-disabled-clients . (rubocop-ls ruby-ls))
                  (projectile-project-type . rails-test)
                  (ruby-test-rails-test-command . "bin/spring rails test")
                  (flycheck-reekrc . "~/.config/jake/projects/meetcleo/meetcleo/reek.yml")))
 (ruby-base-mode . ((lsp-sorbet-use-bundler . t)
                    (lsp-sorbet-as-add-on . t)
                    (lsp-disabled-clients . (rubocop-ls ruby-ls))
                    (projectile-project-type . rails-test)
                    (ruby-test-rails-test-command . "bin/spring rails test")
                    (flycheck-reekrc . "~/.config/jake/projects/meetcleo/meetcleo/reek.yml")))
 (ruby-mode . ((lsp-sorbet-use-bundler . t)
               (lsp-sorbet-as-add-on . t)
               (lsp-disabled-clients . (rubocop-ls ruby-ls))
               (projectile-project-type . rails-test)
               (ruby-test-rails-test-command . "bin/spring rails test")
               (flycheck-reekrc . "~/.config/jake/projects/meetcleo/meetcleo/reek.yml")))
 (nil . ((eval . (setq flycheck-javascript-eslint-executable
                       (concat (projectile-project-root) "node_modules/.bin/eslint"))))))
