# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt autocd
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.config/zsh/zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

export CLAUDE_CONFIG_DIR="$XDG_CONFIG_HOME/claude"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export HOMESICKDIR="$XDG_DATA_HOME/homesick"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"
export SPACEMACSDIR="$XDG_CONFIG_HOME/spacemacs"
export ZSH="$XDG_DATA_HOME/oh-my-zsh"
# export KUBECONFIG="$XDG_CONFIG_HOME/kube/settings."

# put zsh at the top so that any clashing aliases we create take priority

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#808080"

plugins=(git extract sudo zsh-autosuggestions z)

source $ZSH/oh-my-zsh.sh

export USER=jake

# secrets
export HOMEBREW_GITHUB_API_TOKEN=$(pass show github/homebrew)
export MISE_GITHUB_TOKEN=$(pass show github/homebrew)

alias f=fzf
alias cat=bat
alias ls="eza --all --long --group"

# cleo
export AWS_PROFILE=Engineer-878877078763
export EAGER_LOAD_TEST_ENVIRONMENT=false
export LOG_PRODUCT_FEATURES_TO_DB=false
export NO_WEBPACK_COMPILE_CHECK=1
export PARALLEL_WORKERS=1
# export RAISE_API_EXCEPTIONS=true
export SKIP_TEST_TIMEOUT=1
export TERRAGRUNT_DOWNLOAD=${HOME}/.terragrunt-cache
export TERRAGRUNT_PROVIDER_CACHE=1
export TERRAGRUNT_PROVIDER_CACHE_DIR="$HOME/.terragrunt-provider-cache"
export TF_PLUGIN_CACHE_DIR=${HOME}/.terraform.d/plugin-cache
alias dracarys="bundle exec rails db:reset data:quick_sync_prod db:seed db:migrate stripe:setup_dev"

# git
alias gadd="git add -N . && git add -p ."
alias gfrm="git fetch && git rebase -i --rebase-merges origin/main --autostash"
alias kapow="git fetch --prune && gpr --autostash && bundle && bundle exec rails db:migrate && gco -- ."

# rails
alias be="bundle exec"
alias r="bundle exec rails"
alias rdbm="bundle exec rails db:migrate"
alias rs="bundle exec rails server"
alias rc="bundle exec rails console"

# rusty bucket
alias rb="cd ~/work/personal/rusty-bucket"

export EDITOR=nvim
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
export SAVEHIST=1000000
export HISTFILE=$XDG_DATA_HOME/zsh/history
setopt APPEND_HISTORY
bindkey "^[^[[D" backward-word
bindkey "^[^[[C" forward-word

# PATH exports
export PATH=$PATH:$XDG_CONFIG_HOME/emacs/bin
export PATH=$PATH:$HOME/.local/bin

source $XDG_CONFIG_HOME/zsh/theme

prompt_context(){}

bindkey -v
# Set block cursor in normal mode
function zle-line-init {
  if [[ $KEYMAP == vicmd ]]; then
    echo -ne '\e[2 q'  # Block cursor (normal mode)
  else
    echo -ne '\e[3 q'  # Underline cursor (insert mode)
  fi
  zle reset-prompt
}

# Reset the cursor shape in insert mode
function zle-keymap-select {
  if [[ $KEYMAP == vicmd ]]; then
    echo -ne '\e[2 q'  # Block cursor (normal mode)
  else
    echo -ne '\e[3 q'  # Underline cursor (insert mode)
  fi
}

zle -N zle-line-init
zle -N zle-keymap-select

case "$(uname)" in
  "Darwin")
    source $XDG_CONFIG_HOME/zsh/local.mac
    ;;
  "Linux")
    source $XDG_CONFIG_HOME/zsh/local.arch
    ;;
esac

eval "$(mise activate zsh)"
