accent = "color: 9963ff"
cursor = "color: 61e2ff"
foreground = "color: 61e2ff"
background = "color: 200933"
selection_foreground = "color: 200933"
selection_background = "color: fad000"

color0 = "color: 200933"
color1 = "color: fc199a"
color2 = "color: a5ff90"
color3 = "color: fad000"
color4 = "color: 9963ff"
color5 = "color: fc199a"
color6 = "color: 61e2ff"
color7 = "color: 9effff"
color8 = "color: 574497"
color9 = "color: fc199a"
color10 = "color: a5ff90"
color11 = "color: fad000"
color12 = "color: 9963ff"
color13 = "color: fc199a"
color14 = "color: 61e2ff"
color15 = "color: 9effff"
