;; -*- lexical-binding: nil -*-

(deftheme jakewave
  "Created 2023-05-27.")

(defun jake-interpolate-color (color1 color2 ratio)
  "Interpolate between COLOR1 and COLOR2 by RATIO."
  (let* ((c1 (color-name-to-rgb color1))
         (c2 (color-name-to-rgb color2))
         (red   (+ (* (- (nth 0 c2) (nth 0 c1)) ratio) (nth 0 c1)))
         (green (+ (* (- (nth 1 c2) (nth 1 c1)) ratio) (nth 1 c1)))
         (blue  (+ (* (- (nth 2 c2) (nth 2 c1)) ratio) (nth 2 c1))))
    (apply 'color-rgb-to-hex (list red green blue))))

(defun jake/color-adjust-lightness (hex amount)
  "Return HEX adjusted by AMOUNT lightness.
AMOUNT is positive to lighten, negative to darken."
  (apply #'color-rgb-to-hex
         (append
          (apply #'color-hsl-to-rgb
                 (let* ((rgb (color-name-to-rgb hex))
                        (hsl (apply #'color-rgb-to-hsl rgb))
                        (h (nth 0 hsl))
                        (s (nth 1 hsl))
                        (l (nth 2 hsl)))
                   (list h s (max 0.0 (min 1.0 (+ l amount))))))
          '(2))))

(defvar jake-black "#1d0432")
(defvar jake-red "#fc199a")
(defvar jake-green "#a5ff90")
(defvar jake-yellow "#fad000")
(defvar jake-blue "#9963ff")
(defvar jake-magenta "#fc199a")
(defvar jake-cyan "#61e2ff")
(defvar jake-white "#61e2ff")

(defvar jake-black-bright "#574497")
(defvar jake-red-bright "#fc199a")
(defvar jake-green-bright "#a5ff90")
(defvar jake-yellow-bright "#fad000")
(defvar jake-blue-bright "#9963ff")
(defvar jake-magenta-bright "#fc199a")
(defvar jake-cyan-bright "#9eefff")
(defvar jake-white-bright "#61e2ff")

(defvar jake-foreground "#61e2ff")
(defvar jake-background "#200933")

(defvar jake-cursor "#fad000")
(defvar jake-accent "#9963ff")

(defvar jake-selection-background "#fad000")
(defvar jake-selection-foreground "#371057")

(defvar jake-background-darker (jake/color-adjust-lightness jake-background -0.01))
(defvar jake-background-lighter (jake/color-adjust-lightness jake-background 0.08))

(let ((jake-fixed "MonaspiceAr NFM")
      (jake-variable "Noto Sans")
      (jake-variable-heading "MonaspiceRn Nerd Font")
      (jake-script "MonaspiceRn Nerd Font")

      (jake-normal-weight 'light)

      (jake-org-2 (jake-interpolate-color jake-yellow jake-cyan 0.0))
      (jake-org-3 (jake-interpolate-color jake-yellow jake-cyan 0.3))
      (jake-org-4 (jake-interpolate-color jake-yellow jake-cyan 0.6))
      (jake-org-5 (jake-interpolate-color jake-yellow jake-cyan 0.7))
      (jake-org-6 (jake-interpolate-color jake-yellow jake-cyan 0.8))
      (jake-org-7 (jake-interpolate-color jake-yellow jake-cyan 0.9))
      (jake-org-8 (jake-interpolate-color jake-yellow jake-cyan 0.95)))


  (defface jake-script `((t (:family ,jake-script))) "jakewave script face.")
  (defface jake-highlight `((t (:background ,jake-background-lighter))) "jakewave dark purple")

  (defface jake-no-glow `((t)) "jakewave non glowing face.")

  (defface jake-black `((t (:foreground ,jake-black))) "jakewave non glowing black face.")
  (defface jake-red `((t (:foreground ,jake-red))) "jakewave non glowing red face.")
  (defface jake-green `((t (:foreground ,jake-green))) "jakewave non glowing green face.")
  (defface jake-yellow `((t (:foreground ,jake-yellow))) "jakewave non glowing yellow face.")
  (defface jake-blue `((t (:foreground ,jake-blue))) "jakewave non glowing blue face.")
  (defface jake-magenta `((t (:foreground ,jake-magenta))) "jakewave non glowing magenta face.")
  (defface jake-cyan `((t (:foreground ,jake-cyan))) "jakewave non glowing cyan face.")
  (defface jake-white `((t (:foreground ,jake-white))) "jakewave non glowing white face.")

  (defface jake-black-bright `((t (:foreground ,jake-black-bright))) "jakewave non glowing black bright face.")
  (defface jake-red-bright `((t (:foreground ,jake-red-bright))) "jakewave non glowing red bright face.")
  (defface jake-green-bright `((t (:foreground ,jake-green-bright))) "jakewave non glowing green bright face.")
  (defface jake-yellow-bright `((t (:foreground ,jake-yellow-bright))) "jakewave non glowing yellow bright face.")
  (defface jake-blue-bright `((t (:foreground ,jake-blue-bright))) "jakewave non glowing blue bright face.")
  (defface jake-magenta-bright `((t (:foreground ,jake-magenta-bright))) "jakewave non glowing magenta bright face.")
  (defface jake-cyan-bright `((t (:foreground ,jake-cyan-bright))) "jakewave non glowing cyan bright face.")
  (defface jake-white-bright `((t (:foreground ,jake-white-bright))) "jakewave non glowing white bright face.")

  (defface jake-foreground `((t (:foreground ,jake-foreground))) "jakewave non glowing foreground face.")
  (defface jake-background `((t (:foreground ,jake-background))) "jakewave non glowing background face.")
  (defface jake-cursor `((t (:foreground ,jake-cursor))) "jakewave non glowing cursor face.")
  (defface jake-accent `((t (:foreground ,jake-accent))) "jakewave non glowing accent face.")
  (defface jake-selection-foreground `((t (:foreground ,jake-selection-foreground))) "jakewave non glowing selection-foreground face.")
  (defface jake-selection-background `((t (:foreground ,jake-selection-background))) "jakewave non glowing selection-background face.")

  (defface jake-black-glow `((t (:foreground ,jake-black))) "jakewave glowing black face.")
  (defface jake-red-glow `((t (:foreground ,jake-red))) "jakewave glowing red face.")
  (defface jake-green-glow `((t (:foreground ,jake-green))) "jakewave glowing green face.")
  (defface jake-yellow-glow `((t (:foreground ,jake-yellow))) "jakewave glowing yellow face.")
  (defface jake-blue-glow `((t (:foreground ,jake-blue))) "jakewave glowing blue face.")
  (defface jake-magenta-glow `((t (:foreground ,jake-magenta))) "jakewave glowing magenta face.")
  (defface jake-cyan-glow `((t (:foreground ,jake-cyan))) "jakewave glowing cyan face.")
  (defface jake-white-glow `((t (:foreground ,jake-white))) "jakewave glowing white face.")

  (defface jake-black-bright-glow `((t (:foreground ,jake-black-bright))) "jakewave glowing black bright face.")
  (defface jake-red-bright-glow `((t (:foreground ,jake-red-bright))) "jakewave glowing red bright face.")
  (defface jake-green-bright-glow `((t (:foreground ,jake-green-bright))) "jakewave glowing green bright face.")
  (defface jake-yellow-bright-glow `((t (:foreground ,jake-yellow-bright))) "jakewave glowing yellow bright face.")
  (defface jake-blue-bright-glow `((t (:foreground ,jake-blue-bright))) "jakewave glowing blue bright face.")
  (defface jake-magenta-bright-glow `((t (:foreground ,jake-magenta-bright))) "jakewave glowing magenta bright face.")
  (defface jake-cyan-bright-glow `((t (:foreground ,jake-cyan-bright))) "jakewave glowing cyan bright face.")
  (defface jake-white-bright-glow `((t (:foreground ,jake-white-bright))) "jakewave glowing white bright face.")

  (custom-theme-set-faces
   'jakewave

   `(ansi-color-black ((t (:foreground ,jake-background :background ,jake-background))))
   `(ansi-color-blue ((t (:foreground ,jake-blue :background ,jake-blue))))
   `(ansi-color-bright-black ((t (:foreground ,jake-black-bright :background ,jake-black-bright))))
   `(ansi-color-bright-blue ((t (:inherit jake-blue-bright-glow :foreground ,jake-blue-bright :background ,jake-blue-bright))))
   `(ansi-color-bright-green ((t (:inherit jake-green-bright-glow :foreground ,jake-green-bright :background ,jake-green-bright))))
   `(ansi-color-bright-magenta ((t (:inherit jake-magenta-bright-glow :foreground ,jake-magenta-bright :background ,jake-magenta-bright))))
   `(ansi-color-bright-red ((t (:inherit jake-red-bright-glow :foreground ,jake-red-bright :background ,jake-red-bright))))
   `(ansi-color-bright-yellow ((t (:inherit jake-yellow-bright-glow :foreground ,jake-yellow-bright :background ,jake-yellow-bright))))
   `(ansi-color-green ((t (:foreground ,jake-green :background ,jake-green))))
   `(ansi-color-magenta ((t (:foreground ,jake-magenta :background ,jake-magenta))))
   `(ansi-color-red ((t (:foreground ,jake-red :background ,jake-red))))
   `(ansi-color-yellow ((t (:foreground ,jake-yellow :background ,jake-yellow))))
   `(avy-background-face ((t (:inherit jake-no-glow :foreground ,jake-foreground :background ,jake-background))))
   `(avy-lead-face ((t (:inherit (jake-megenta-glow bold) :foreground unspecified :background ,jake-background))))
   `(avy-lead-face-0 ((t (:inherit (jake-yellow-glow avy-lead-face) :foreground unspecified :background ,jake-background))))
   `(avy-lead-face-1 ((t (:inherit (jake-green-glow avy-lead-face) :foreground unspecified :background ,jake-background))))
   `(avy-lead-face-2 ((t (:inherit (jake-blue-glow avy-lead-face) :foreground unspecified :background ,jake-background))))
   `(bold ((t (:weight normal))))
   `(button ((t (:inherit (link)))))
   `(calendar-today ((t (:inherit jake-green-glow :foreground unspecified))))
   `(calendar-weekday-header ((t (:inherit jake-megenta-glow :foreground unspecified))))
   `(calendar-weekend-header ((t (:inherit calendar-weekday-header :foreground unspecified))))
   `(company-preview ((t :inherit (jake-highlight jake-black-bright-glow) :foreground unspecified :background unspecified)))
   `(company-tooltip ((t :inherit jake-highlight :foreground ,jake-cyan :background unspecified)))
   `(company-tooltip-annotation ((t :inherit jake-yellow :foreground unspecified :background unspecified)))
   `(company-tooltip-annotation-selection ((t :inherit jake-yellow-glow :foreground unspecified :background unspecified)))
   `(company-tooltip-common ((t :inherit jake-green :foreground unspecified :background unspecified)))
   `(company-tooltip-common-selection ((t :inherit jake-green-glow :foreground unspecified :background unspecified)))
   `(company-tooltip-selection ((t :inherit (bold jake-cyan-glow) :foreground unspecified :background unspecified)))
   `(compilation-mode-line-fail ((t (:foreground ,jake-red))))
   `(completions-annotations ((t :inherit (jake-blue jake-script) :foreground unspecified)))
   `(consult-file ((t :inherit jake-foreground :foreground unspecified :weight ,jake-normal-weight)))
   `(consult-help ((t :inherit jake-blue :foreground unspecified)))
   `(consult-highlight-match ((t :inherit jake-green-glow :foreground unspecified :background unspecified)))
   `(consult-line-number ((t :inherit jake-yellow-glow :foreground unspecified :background unspecified)))
   `(cursor ((t (:background ,jake-cursor))))
   `(default ((t (:inherit nil :family ,jake-fixed :stipple nil :background ,jake-background :foreground ,jake-foreground :inverse-video nil :box nil :strike-through nil :extend nil :overline nil :underline nil :shadow nil :slant normal :weight light :width normal :foundry "nil"))))
   `(diff-added ((t (:foreground ,jake-green))))
   `(diff-context ((t (:foreground ,jake-black-bright))))
   `(diff-hl-change ((t (:background ,jake-yellow :foreground ,jake-background-darker))))
   `(diff-hl-delete ((t (:background ,jake-red :foreground ,jake-background-darker))))
   `(diff-hl-insert ((t (:background ,jake-green :foreground ,jake-background-darker))))
   `(diff-removed ((t (:foreground ,jake-red))))
   `(dired-directory ((t (:inherit (font-lock-constant-face) :foreground unspecified :background unspecified))))
   `(diredfl-compressed-file-suffix ((t (:inherit jake-green-glow) :foreground unspecified)))
   `(diredfl-date-time ((t (:inherit jake-blue-glow :foreground unspecified))))
   `(diredfl-deletion ((t (:inherit (jake-red-glow bold) :foreground unspecified :background unspecified))))
   `(diredfl-deletion-file-name ((t (:inherit jake-black-bright-glow :foreground unspecified))))
   `(diredfl-dir-heading ((t (:inherit jake-magenta-glow :foreground unspecified))))
   `(diredfl-dir-name ((t (:inherit jake-magenta-glow :foreground unspecified))))
   `(diredfl-dir-priv ((t (:inherit jake-yellow-glow :foreground unspecified))))
   `(diredfl-exec-priv ((t (:inherit jake-blue-glow :foreground unspecified))))
   `(diredfl-file-name ((t (:inherit jake-yellow-glow :foreground unspecified))))
   `(diredfl-file-suffix ((t (:inherit jake-green-glow  :foreground unspecified))))
   `(diredfl-ignored-file-name ((t (:inherit jake-black-bright-glow :foreground unspecified))))
   `(diredfl-link-priv ((t (:inherit jake-yellow-glow :foreground unspecified))))
   `(diredfl-no-priv ((t (:inherit jake-black-bright-glow :foreground unspecified))))
   `(diredfl-number ((t (:inherit jake-yellow-glow :foreground unspecified))))
   `(diredfl-read-priv ((t (:inherit jake-green-glow :foreground unspecified))))
   `(diredfl-symlink ((t (:inherit jake-blue-glow :foreground unspecified))))
   `(diredfl-write-priv ((t (:inherit jake-magenta-glow :foreground unspecified))))
   `(doom-modeline-bar ((t (:background ,jake-blue))))
   `(doom-modeline-bar-inactive ((t (:background ,jake-background-lighter))))
   `(doom-modeline-buffer-file ((t (:inherit jake-green-glow :foreground unspecified))))
   `(doom-modeline-buffer-modified ((t (:inherit jake-red-glow :foreground unspecified))))
   `(doom-modeline-error ((t (:inherit jake-red))))
   `(doom-modeline-evil-insert-state ((t (:inherit jake-blue))))
   `(doom-modeline-evil-motion-state ((t (:inherit jake-cyan))))
   `(doom-modeline-evil-normal-state ((t (:inherit jake-green))))
   `(doom-modeline-info ((t (:inherit jake-green-glow :foreground unspecified))))
   `(doom-modeline-project-dir ((t (:inherit jake-blue-glow :foreground unspecified))))
   `(doom-modeline-warning ((t (:inherit jake-yellow))))
   `(error ((t (:foreground ,jake-red))))
   `(escape-glyph ((t (:foreground "#9EFFFF"))))
   `(evil-ex-lazy-highlight ((t (:inherit (jake-no-glow bold) :foreground ,jake-background :background ,jake-green))))
   `(fixed-pitch ((t (:family ,jake-fixed))))
   `(font-lock-bracket-face ((t (:inherit font-lock-punctuation-face :foreground unspecified))))
   `(font-lock-builtin-face ((t (:inherit jake-magenta-glow :foreground unspecified))))
   `(font-lock-comment-delimiter-face ((default (:inherit font-lock-comment-face))))
   `(font-lock-comment-face ((t (:inherit (jake-script jake-black-bright-glow) :foreground unspecified :background unspecified))))
   `(font-lock-constant-face ((t (:foreground ,jake-blue))))
   `(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
   `(font-lock-doc-face ((t (:inherit (jake-script jake-blue-glow) :foreground unspecified))))
   `(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
   `(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
   `(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
   `(font-lock-function-name-face ((t (:inherit (jake-yellow-glow bold) :foreground unspecified))))
   `(font-lock-keyword-face ((t (:inherit (jake-magenta-glow bold) :foreground unspecified :slant normal))))
   `(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face) :foreground unspecified))))
   `(font-lock-negation-char-face ((t (:foreground "#a45bad"))))
   `(font-lock-number-face ((t nil)))
   `(font-lock-operator-face ((t (:inherit (font-lock-keyword-face) :foreground unspecified))))
   `(font-lock-preprocessor-face ((t (:inherit jake-magenta-glow :foreground unspecified))))
   `(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
   `(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
   `(font-lock-punctuation-face ((t (:inherit (font-lock-keyword-face) :foreground unspecified))))
   `(font-lock-punctuation-face ((t nil)))
   `(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
   `(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
   `(font-lock-string-face ((t (:inherit jake-green-glow :foreground unspecified))))
   `(font-lock-type-face ((t (:inherit (jake-yellow-glow bold) :foreground unspecified))))
   `(font-lock-variable-name-face ((t (:inherit (jake-cyan-glow bold) :foreground unspecified))))
   `(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
   `(font-lock-warning-face ((t (:foreground "#dc752f" :background "#292b2e"))))
   `(fringe ((t (:background "#1d0432" :foreground "#520c8b"))))
   `(git-commit-keyword ((t (:inherit jake-no-glow))))
   `(gnus-header-content ((t (:foreground ,jake-blue))))
   `(gnus-header-from ((t (:inherit jake-yellow-glow :foreground unspecified :weight ,jake-normal-weight))))
   `(gnus-header-name ((t (:foreground ,jake-magenta))))
   `(gnus-header-subject ((t (:inherit jake-green-glow :foreground unspecified))))
   `(header-line ((t (:background ,jake-background-lighter :overline ,jake-blue))))
   `(helm-M-x-key ((t :inherit jake-green-glow :foreground unspecified :box t)))
   `(helm-command-active-mode ((t :inherit jake-yellow-glow :foreground unspecified)))
   `(helm-ff-directory ((t :inherit jake-yellow-glow :foreground unspecified :background unspecified)))
   `(helm-ff-dotted-symlink-direcroty ((t :inherit jake-blue-glow :foreground unspecified :background unspecified)))
   `(helm-ff-executable ((t :inherit jake-green :foreground unspecified :background unspecified)))
   `(helm-ff-file ((t :inherit jake-cyan :weight ,jake-normal-weight :foreground unspecified :background unspecified)))
   `(helm-ff-file-extension ((t :inherit jake-cyan-glow :foreground unspecified :background unspecified)))
   `(helm-ff-symlink ((t :inherit jake-blue :foreground unspecified :background unspecified)))
   `(helm-grep-lineno ((t :inherit jake-yellow-glow :foreground unspecified :background unspecified)))
   `(helm-match ((t :inherit jake-green-glow :foreground unspecified :background unspecified)))
   `(helm-match-item ((t (:inherit (jake-no-glow bold) :foreground ,jake-background :background ,jake-green))))
   `(helm-moccur-buffer ((t :inherit jake-yellow-glow :foreground unspecified :background unspecified)))
   `(helm-posframe-border ((t :background ,jake-yellow)))
   `(helm-selection ((t :inherit jake-highlight :background unspecified)))
   `(helm-selection-line ((t :inherit jake-highlight :background unspecified)))
   `(helm-source-header ((t :inherit (jake-script jake-magenta-glow) :foreground unspecified :background unspecified :underline ,jake-magenta)))
   `(highlight ((t (:foreground unspecified :background unspecified))))
   `(highlight-numbers-number ((t :inherit jake-magenta-glow)))
   `(highlight-parentheses-highlight ((t (:inherit bold))))
   `(hl-line ((t (:background ,jake-background-lighter))))
   `(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
   `(info-double-quoted-name ((t (:inherit jake-yellow-glow :foreground unspecified))))
   `(info-glossary-word ((t (:inherit link :foreground unspecified :underline t :box unspecified))))
   `(info-header-node ((t (:inherit jake-magenta-glow :foreground unspecified))))
   `(info-header-xref ((t (:inherit jake-magenta-glow :foreground unspecified))))
   `(info-menu-header ((t (:inherit (variable-pitch jake-yellow bold) :foreground unspecified :weight normal))))
   `(info-quoted-name ((t (:inherit (jake-yellow-glow fixed-pitch) :foreground unspecified :background ,jake-background-lighter))))
   `(info-string ((t (:inherit jake-green-glow :foreground unspecified))))
   `(info-xref ((t (:inherit link :foreground unspecified :underline t))))
   `(info-xref-visited ((t (:inherit jake-blue-glow :foreground unspecified :underline t))))
   `(isearch ((t (:foreground "#2D2B55" :background "#FF7300"))))
   `(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
   `(js2-external-variable ((t (:foreground unspecified))))
   `(js2-function-call ((t (:inherit web-mode-function-call-face :foreground unspecified))))
   `(js2-function-param ((t (:inherit font-lock-constant-face :foreground unspecified))))
   `(lazy-highlight ((t (:weight normal :background "#FFFF03" :inherit (isearch)))))
   `(line-number ((t (:inherit (fixed-pitch) :background ,jake-background-darker :foreground "#4A1E64"))))
   `(line-number-current-line ((t (:inherit bold :background ,jake-background-darker :foreground "#7912CE" :weight unspecified))))
   `(link ((t (:inherit jake-cyan-bright-glow :underline (:color foreground-color :style line :position nil) :foreground unspecified))))
   `(link-visited ((t (:underline (:color foreground-color :style line :position nil) :foreground "#c56ec3"))))
   `(lsp-flycheck-error-unnecessary-face ((t (:inherit jake-black-bright-glow :foreground unspecified))))
   `(lsp-flycheck-info-unnecessary-face ((t (:inherit jake-black-bright-glow :foreground unspecified))))
   `(lsp-flycheck-warning-unnecessary-face ((t (:inherit jake-black-bright-glow :foreground unspecified))))
   `(lsp-headerline-breadcrumb-path-face ((t (:inherit (font-lock-constant-face)))))
   `(lsp-headerline-breadcrumb-symbols-face ((t (:inherit (font-lock-type-face)))))
   `(lsp-ui-doc-background ((t :background ,jake-background)))
   `(lsp-ui-peek-filename ((t :inherit jake-magenta-glow :foreground unspecified)))
   `(lsp-ui-peek-footer ((t :inherit lsp-ui-peek-header :background unspecified :foreground unspecified)))
   `(lsp-ui-peek-header ((t :inherit (header-line jake-yellow-glow) :background unspecified :foreground unspecified)))
   `(lsp-ui-peek-highlight ((t :inherit (jake-green-glow bold) :background unspecified :foreground unspecified)))
   `(lsp-ui-peek-list ((t :background unspecified :foreground ,jake-yellow)))
   `(lsp-ui-peek-peek ((t :background unspecified :foreground unspecified)))
   `(lsp-ui-peek-selection ((t :inherit (hl-line jake-yellow-glow) :background unspecified :foreground unspecified)))
   `(magit-blame-date (( t (:background unspecified :foreground ,jake-black-bright))))
   `(magit-blame-heading (( t (:background ,jake-background-darker :overline ,jake-black-bright :foreground ,jake-black-bright))))
   `(magit-blame-name (( t (:background unspecified :foreground ,jake-black-bright))))
   `(magit-blame-summary (( t (:background unspecified :foreground ,jake-black-bright))))
   `(magit-branch-local ((t :inherit jake-yellow-glow :foreground unspecified :background unspecified)))
   `(magit-branch-remote ((t :inherit jake-green-glow :foreground unspecified :background unspecified)))
   `(magit-diff-hunk-heading ((t (:inherit jake-black-bright-glow :foreground ,jake-black-bright :background ,jake-background :underline t))))
   `(magit-diff-hunk-heading-highlight ((t (:inherit jake-blue-glow :foreground unspecified :background ,jake-background :underline t))))
   `(magit-diff-revision-summary-highlight ((t (:inherit jake-magenta-glow :foreground unspecified))))
   `(magit-section-highlight ((t :inherit jake-highlight :background unspecified)))
   `(markdown-code-face ((t :inherit org-verbatim :height 1)))
   `(markdown-header-face-1 ((t :inherit org-level-1 :foreground unspecified)))
   `(markdown-header-face-2 ((t :inherit org-level-2 :foreground unspecified)))
   `(markdown-header-face-3 ((t :inherit org-level-3 :foreground unspecified)))
   `(markdown-header-face-4 ((t :inherit org-level-4 :foreground unspecified)))
   `(markdown-header-face-5 ((t :inherit org-level-5 :foreground unspecified)))
   `(markdown-header-face-6 ((t :inherit org-level-6 :foreground unspecified)))
   `(markdown-list-face ((t :inherit jake-blue-glow :background unspecified)))
   `(markdown-markup-face ((t :inherit org-block :background unspecified)))
   `(match ((t :inherit (jake-green-glow bold) :background unspecified :foreground unspecified)))
   `(minibuffer-prompt ((t (:foreground ,jake-yellow :inherit (bold)))))
   `(mode-line ((t (:box (:line-width (1 . 1) :color ,jake-blue :style nil) :overline nil :inherit jake-yellow-glow :foreground unspecified :background ,jake-background-lighter))))
   `(mode-line-buffer-id ((t (:foreground "#bc6ec5" :inherit (bold)))))
   `(mode-line-emphasis ((t (:inherit bold))))
   `(mode-line-highlight ((((supports :box t) (class color) (min-colors 88)) (:box (:line-width (2 . 2) :color "grey40" :style released-button))) (t (:inherit (jake-highlight)))))
   `(mode-line-inactive ((t (:weight light :box (:line-width (1 . 1) :color ,jake-black-bright :style nil) :inherit jake-black-bright-glow :foreground unspecified :background ,jake-background))))
   `(mu4e-flagged-face ((t (:inherit jake-yellow-glow :foreground unspecified :weight ,jake-normal-weight))))
   `(mu4e-header-face ((t (:foreground ,jake-blue))))
   `(mu4e-header-highlight-face ((t (:inherit jake-highlight :background unspecified))))
   `(mu4e-header-key-face ((t (:inherit jake-yellow-glow :foreground unspecified))))
   `(mu4e-header-title-face ((t (:inherit jake-blue-glow :foreground unspecified))))
   `(mu4e-highlight-face ((t (:inherit (jake-magenta-glow bold) :foreground unspecified))))
   `(mu4e-related-face ((t (:inherit (mu4e-header-face)))))
   `(mu4e-replied-face ((t (:inherit (mu4e-header-face) :foreground ,jake-blue))))
   `(mu4e-title-face ((t (:inherit jake-green-glow :foreground unspecified))))
   `(mu4e-unread-face ((t (:inherit jake-yellow-glow :foreground unspecified :weight ,jake-normal-weight))))
   `(next-error ((t (:weight normal :inherit (error)))))
   `(orderless-match-face-0 ((t :inherit jake-green-glow :foreground unspecified :weight ,jake-normal-weight)))
   `(orderless-match-face-1 ((t :inherit orderless-match-face-0 :foreground unspecified)))
   `(orderless-match-face-2 ((t :inherit orderless-match-face-0 :foreground unspecified)))
   `(orderless-match-face-3 ((t :inherit orderless-match-face-0 :foreground unspecified)))
   `(org-agenda-calendar-event ((t (:inherit org-agenda-done :foreground unspecified))))
   `(org-agenda-date ((t (:inherit (jake-script jake-blue) :height 1.2 :foreground unspecified))))
   `(org-agenda-date-today ((t (:inherit (jake-yellow-glow org-agenda-date) :foreground unspecified))))
   `(org-agenda-date-weekend ((t (:inherit org-agenda-date :foreground unspecified))))
   `(org-agenda-date-weekend-today ((t (:inherit org-agenda-date-today :foreground unspecified))))
   `(org-agenda-done ((t (:inherit jake-script :foreground ,jake-black-bright :strike-through t))))
   `(org-agenda-structure ((t (:inherit (jake-script jake-magenta-glow) :height 1.5 :foreground unspecified))))
   `(org-block ((t (:inherit (fixed-pitch) :background ,jake-background-lighter :height 0.75 ))))
   `(org-block-begin-line ((t (:inherit (fixed-pitch jake-black-bright-glow) :foreground unspecified :background ,jake-background-lighter :height 0.75))))
   `(org-block-end-line ((t (:inherit (fixed-pitch) :foreground ,jake-black-bright :background ,jake-background-lighter :height 0.75))))
   `(org-checkbox ((t (:inherit jake-green-glow :family ,jake-fixed :foreground unspecified))))
   `(org-checkbox-statistics-done ((t (:inherit (fixed-pitch) :foreground ,jake-green))))
   `(org-checkbox-statistics-todo ((t (:inherit (fixed-pitch) :foreground ,jake-red))))
   `(org-code ((t (:inherit (fixed-pitch) :background ,jake-background-lighter :foreground ,jake-magenta :height 0.75))))
   `(org-date ((t (:inherit (jake-script jake-black-bright) :foreground unspecified :underline unspecified))))
   `(org-date-selected ((t (:foreground ,jake-background :background ,jake-yellow))))
   `(org-document-info ((t :inherit org-tag :foreground unspecified)))
   `(org-document-info-keyword ((t :inherit org-tag :foreground unspecified)))
   `(org-document-title ((t :inherit org-tag :foreground unspecified :underline unspecified)))
   `(org-done ((t (:inherit jake-green-glow :background unspecified :foreground unspecified :family ,jake-script :height 0.75 :weight thin))))
   `(org-drawer ((t (:inherit (jake-script jake-black-bright) :background unspecified :foreground unspecified))))
   `(org-ellipsis ((t (:inherit jake-green-glow :foreground unspecified))))
   `(org-indent ((t (:inherit (org-hide fixed-pitch)))))
   `(org-journal-calendar-entry-face ((t (:foreground unspecified))))
   `(org-level-1 ((t (:family ,jake-variable-heading :inherit jake-magenta-glow :foreground unspecified :height 2.0))))
   `(org-level-2 ((t (:family ,jake-variable-heading :foreground ,jake-org-2 :height 1.5))))
   `(org-level-3 ((t (:family ,jake-variable-heading :foreground ,jake-org-3 :height 1.25))))
   `(org-level-4 ((t (:family ,jake-variable-heading :foreground ,jake-org-4 :height 1.1))))
   `(org-level-5 ((t (:family ,jake-variable-heading :foreground ,jake-org-5 :height 1.1))))
   `(org-level-6 ((t (:family ,jake-variable-heading :foreground ,jake-org-6 :height 1.1))))
   `(org-level-7 ((t (:family ,jake-variable-heading :foreground ,jake-org-7 :height 1.1))))
   `(org-level-8 ((t (:family ,jake-variable-heading :foreground ,jake-org-8 :height 1.1))))
   `(org-link ((t (:inherit (jake-cyan-bright-glow) :foreground unspecified :underline unspecified))))
   `(org-meta-line ((t (:inherit (fixed-pitch) :foreground ,jake-black-bright :background unspecified :height 0.75))))
   `(org-priority ((t (:inherit (jake-script jake-blue) :foreground unspecified :height 0.75 :weight ,jake-normal-weight))))
   `(org-scheduled ((t (:inherit jake-script :foreground ,jake-cyan :slant unspecified))))
   `(org-scheduled-previously ((t (:inherit jake-script :foreground ,jake-black-bright :slant unspecified))))
   `(org-scheduled-today ((t (:inherit jake-script :foreground ,jake-green :slant unspecified))))
   `(org-special-keyword ((t (:inherit jake-black-bright :foreground unspecified :family ,jake-script))))
   `(org-superstar-item ((t (:inherit (fixed-pitch) :foreground ,jake-magenta))))
   `(org-superstar-leading ((t (:inherit (fixed-pitch) :foreground ,jake-background))))
   `(org-table ((t (:inherit (fixed-pitch) :foreground ,jake-magenta :background ,jake-background-lighter :height 0.75))))
   `(org-tag ((t (:inherit (jake-script jake-black-bright) :foreground unspecified :height 0.75 :weight ,jake-normal-weight))))
   `(org-todo ((t (:inherit jake-red-glow :background unspecified :foreground unspecified :family ,jake-script :height 0.75 :weight thin))))
   `(org-verbatim ((t (:inherit (fixed-pitch jake-yellow-glow) :foreground unspecified :background ,jake-background-lighter :weight ,jake-normal-weight :height 0.75))))
   `(origami-fold-header-face ((t)))
   `(query-replace ((t (:inherit (isearch)))))
   `(rainbow-delimiters-depth-1-face ((t (:inherit (jake-magenta) :foreground unspecified))))
   `(rainbow-delimiters-depth-2-face ((t (:inherit (jake-yellow) :foreground unspecified))))
   `(rainbow-delimiters-depth-3-face ((t (:inherit (jake-green) :foreground unspecified))))
   `(rainbow-delimiters-depth-4-face ((t (:inherit (jake-cyan) :foreground unspecified))))
   `(rainbow-delimiters-depth-5-face ((t (:inherit (jake-blue) :foreground unspecified))))
   `(rainbow-delimiters-depth-6-face ((t (:inherit rainbow-delimiters-depth-1-face :foreground unspecified))))
   `(rainbow-delimiters-depth-7-face ((t (:inherit rainbow-delimiters-depth-2-face :foreground unspecified))))
   `(rainbow-delimiters-depth-8-face ((t (:inherit rainbow-delimiters-depth-3-face :foreground unspecified))))
   `(rainbow-delimiters-depth-9-face ((t (:inherit rainbow-delimiters-depth-4-face :foreground unspecified))))
   `(region ((t (:inherit jake-no-glow :foreground ,jake-background-lighter :background ,jake-yellow))))
   `(rjsx-attr ((t (:inherit web-mode-html-attr-name-face :foreground unspecified))))
   `(rjsx-tag-bracket-face ((t (:inherit web-mode-html-tag-bracket-face :foreground unspecified))))
   `(secondary-selection ((t (:extend t :background "#100a14"))))
   `(shadow ((t (:foreground "#494685"))))
   `(show-paren-match ((t (:foreground unspecified))))
   `(smerge-base ((t (:background ,jake-background-lighter))))
   `(smerge-lower ((t (:background ,jake-background-lighter))))
   `(smerge-markers ((t (:inherit font-lock-comment-face :background ,jake-background :foreground unspecified :weight normal :slant normal))))
   `(smerge-refined-added ((t (:inherit jake-green-glow :background unspecified :foreground unspecified))))
   `(smerge-refined-changed ((t (:inherit jake-green-glow :background unspecified :foreground ,jake-green))))
   `(smerge-refined-removed ((t (:inherit jake-red-glow :background unspecified :foreground unspecified))))
   `(smerge-upper ((t (:background ,jake-background-lighter))))
   `(sp-show-pair-match-face ((t (:foreground unspecified))))
   `(term ((t (:inherit default :foreground ,jake-foreground :background ,jake-background :weight unspecified))))
   `(term-color-black ((t (:foreground ,jake-black :background ,jake-black))))
   `(term-color-blue ((t (:foreground ,jake-blue :background ,jake-blue))))
   `(term-color-bright-black ((t (:foreground ,jake-black-bright :background ,jake-black-bright))))
   `(term-color-bright-blue ((t (:inherit (term-color-blue bold) :foreground unspecified :background unspecified :weight unspecified))))
   `(term-color-bright-green ((t (:inherit (term-color-green bold) :foreground unspecified :background unspecified :weight unspecified))))
   `(term-color-bright-yellow ((t (:inherit (bold term-color-yellow) :foreground unspecified :background unspecified :weight unspecified))))
   `(term-color-green ((t (:foreground ,jake-green :background ,jake-green))))
   `(term-color-red ((t (:inherit jake-red-glow :foreground unspecified :background ,jake-red))))
   `(term-color-white ((t (:foreground ,jake-white :background ,jake-white))))
   `(term-color-yellow ((t (:foreground ,jake-yellow :background ,jake-yellow))))
   `(tide-hl-identifier-face ((t (:foreground unspecified :background ,jake-background-lighter))))
   `(tooltip ((t (:inherit (jake-magenta-glow jake-script) :foreground ,jake-magenta :background ,jake-background-lighter))))
   `(trailing-whitespace ((t (:background "#2aa1ae"))))
   `(transient-argument ((t (:inherit jake-green-glow))))
   `(transient-inactive-argument ((t (:inherit jake-blue-glow :foreground unspecified))))
   `(transient-posframe ((t :background ,jake-background-lighter)))
   `(transient-posframe-border ((t :background ,jake-yellow)))
   `(variable-pitch ((t (:family ,jake-variable :height 1.3 :weight light))))
   `(vertical-border ((t (:foreground "#4a1e64"))))
   `(vertico-current ((t (:inherit jake-highlight))))
   `(vertico-group-separator ((t :inherit (jake-script jake-magenta-glow) :foreground unspecified :background unspecified :underline ,jake-magenta)))
   `(vertico-group-title ((t :inherit (jake-script jake-magenta-glow) :foreground unspecified :background unspecified :underline ,jake-magenta)))
   `(vterm-color-black ((t (:foreground ,jake-background :background ,jake-background))))
   `(vterm-color-blue ((t (:foreground ,jake-blue :background ,jake-blue))))
   `(vterm-color-green ((t (:foreground ,jake-green :background ,jake-green))))
   `(vterm-color-red ((t (:foreground ,jake-red :background ,jake-red))))
   `(vterm-color-yellow ((t (:foreground ,jake-yellow :background ,jake-yellow))))
   `(warning ((t (:inherit jake-yellow :foreground unspecified))))
   `(web-mode-html-attr-equal-face ((t (:inherit (jake-magenta-glow bold) :foreground unspecified))))
   `(web-mode-html-attr-name-face ((t (:inherit jake-blue-glow :foreground unspecified))))
   `(web-mode-html-attr-value-face ((t :inherit jake-green-glow :foreground unspecified)))
   `(web-mode-html-tag-bracket-face ((t (:inherit (jake-magenta-glow bold) :foreground unspecified))))
   `(web-mode-html-tag-face ((t (:inherit (jake-yellow-glow) :foreground unspecified))))
   `(web-mode-keyword-face ((t (:inherit (font-lock-keyword-face) :foreground unspecified))))
   `(web-mode-string-face ((t (:inherit (font-lock-string-face) :foreground unspecified))))
   `(web-mode-symbol-face ((t (:inherit font-lock-constant-face :foreground unspecified))))
   `(web-mode-variable-name-face ((t :foreground unspecified)))
   `(which-key-command-description-face ((t :inherit jake-cyan :foreground unspecified)))
   `(which-key-group-description-face ((t :inherit jake-yellow-glow :foreground unspecified)))
   `(which-key-key-face ((t :inherit (jake-magenta-glow bold) :foreground unspecified)))
   `(which-key-posframe ((t :background ,jake-background-lighter)))
   `(which-key-posframe-border ((t :background ,jake-yellow)))
   `(which-key-separator-face ((t :inherit jake-green-glow :foreground unspecified)))
   `(widget-button ((t :inherit bold :weight unspecified)))
   ))

(setq xterm-color-names
      (vconcat (list jake-black jake-red jake-green jake-yellow jake-blue jake-magenta jake-cyan jake-white)))
(setq xterm-color-names-bright
      (vconcat (list jake-black-bright jake-red-bright jake-green-bright jake-yellow-bright jake-blue-bright jake-magenta-bright jake-cyan-bright jake-white-bright)))

(set-face-attribute 'jake-no-glow nil :shadow nil)

(set-face-attribute 'line-number nil :shadow '(10.0 "#4A1E64" 0 . 0))
(set-face-attribute 'line-number-current-line nil :shadow '(10.0 "#7912ce" 0 . 0))

(set-face-attribute 'jake-black nil :shadow nil)
(set-face-attribute 'jake-red nil :shadow nil)
(set-face-attribute 'jake-green nil :shadow nil)
(set-face-attribute 'jake-yellow nil :shadow nil)
(set-face-attribute 'jake-blue nil :shadow nil)
(set-face-attribute 'jake-magenta nil :shadow nil)
(set-face-attribute 'jake-cyan nil :shadow nil)
(set-face-attribute 'jake-white nil :shadow nil)

(set-face-attribute 'jake-black-bright nil :shadow nil)
(set-face-attribute 'jake-red-bright nil :shadow nil)
(set-face-attribute 'jake-green-bright nil :shadow nil)
(set-face-attribute 'jake-yellow-bright nil :shadow nil)
(set-face-attribute 'jake-blue-bright nil :shadow nil)
(set-face-attribute 'jake-magenta-bright nil :shadow nil)
(set-face-attribute 'jake-cyan-bright nil :shadow nil)
(set-face-attribute 'jake-white-bright nil :shadow nil)

(set-face-attribute 'jake-black-glow nil :shadow `(10.0 ,jake-black 0 . 0))
(set-face-attribute 'jake-red-glow nil :shadow `(10.0 ,jake-red 0 . 0))
(set-face-attribute 'jake-green-glow nil :shadow `(10.0 ,jake-green 0 . 0))
(set-face-attribute 'jake-yellow-glow nil :shadow `(10.0 ,jake-yellow 0 . 0))
(set-face-attribute 'jake-blue-glow nil :shadow `(10.0 ,jake-blue 0 . 0))
(set-face-attribute 'jake-magenta-glow nil :shadow `(10.0 ,jake-magenta 0 . 0))
(set-face-attribute 'jake-cyan-glow nil :shadow `(10.0 ,jake-cyan 0 . 0))
(set-face-attribute 'jake-white-glow nil :shadow `(10.0 ,jake-white 0 . 0))

(set-face-attribute 'jake-black-bright-glow nil :shadow `(10.0 ,jake-black-bright 0 . 0))
(set-face-attribute 'jake-red-bright-glow nil :shadow `(10.0 ,jake-red-bright 0 . 0))
(set-face-attribute 'jake-green-bright-glow nil :shadow `(10.0 ,jake-green-bright 0 . 0))
(set-face-attribute 'jake-yellow-bright-glow nil :shadow `(10.0 ,jake-yellow-bright 0 . 0))
(set-face-attribute 'jake-blue-bright-glow nil :shadow `(10.0 ,jake-blue-bright 0 . 0))
(set-face-attribute 'jake-magenta-bright-glow nil :shadow `(10.0 ,jake-magenta-bright 0 . 0))
(set-face-attribute 'jake-cyan-bright-glow nil :shadow `(10.0 ,jake-cyan-bright 0 . 0))
(set-face-attribute 'jake-white-bright-glow nil :shadow `(10.0 ,jake-white-bright 0 . 0))

(set-face-attribute 'nerd-icons-blue nil :shadow nil)
(set-face-attribute 'nerd-icons-blue-alt nil :shadow nil)
(set-face-attribute 'nerd-icons-cyan nil :shadow nil)
(set-face-attribute 'nerd-icons-cyan-alt nil :shadow nil)
(set-face-attribute 'nerd-icons-dblue nil :shadow nil)
(set-face-attribute 'nerd-icons-dcyan nil :shadow nil)
(set-face-attribute 'nerd-icons-dgreen nil :shadow nil)
(set-face-attribute 'nerd-icons-dmaroon nil :shadow nil)
(set-face-attribute 'nerd-icons-dorange nil :shadow nil)
(set-face-attribute 'nerd-icons-dpink nil :shadow nil)
(set-face-attribute 'nerd-icons-dpurple nil :shadow nil)
(set-face-attribute 'nerd-icons-dred nil :shadow nil)
(set-face-attribute 'nerd-icons-dsilver nil :shadow nil)
(set-face-attribute 'nerd-icons-dyellow nil :shadow nil)
(set-face-attribute 'nerd-icons-green nil :shadow nil)
(set-face-attribute 'nerd-icons-lblue nil :shadow nil)
(set-face-attribute 'nerd-icons-lcyan nil :shadow nil)
(set-face-attribute 'nerd-icons-lgreen nil :shadow nil)
(set-face-attribute 'nerd-icons-lmaroon nil :shadow nil)
(set-face-attribute 'nerd-icons-lorange nil :shadow nil)
(set-face-attribute 'nerd-icons-lpink nil :shadow nil)
(set-face-attribute 'nerd-icons-lpurple nil :shadow nil)
(set-face-attribute 'nerd-icons-lred nil :shadow nil)
(set-face-attribute 'nerd-icons-lsilver nil :shadow nil)
(set-face-attribute 'nerd-icons-lyellow nil :shadow nil)
(set-face-attribute 'nerd-icons-maroon nil :shadow nil)
(set-face-attribute 'nerd-icons-orange nil :shadow nil)
(set-face-attribute 'nerd-icons-pink nil :shadow nil)
(set-face-attribute 'nerd-icons-purple nil :shadow nil)
(set-face-attribute 'nerd-icons-purple-alt nil :shadow nil)
(set-face-attribute 'nerd-icons-red nil :shadow nil)
(set-face-attribute 'nerd-icons-red-alt nil :shadow nil)
(set-face-attribute 'nerd-icons-silver nil :shadow nil)
(set-face-attribute 'nerd-icons-yellow nil :shadow nil)

(provide-theme 'jakewave)
